name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Go ${{ matrix.go-ver }} on ${{ matrix.vm-os }}
    runs-on: ${{ matrix.vm-os }}
    strategy:
      fail-fast: false
      matrix:
        vm-os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12, macos-13, windows-2019, windows-2022]
        go-ver:
          - "1.13.15"
          - "1.14.15"
          - "1.15.15"
          - "1.16.15"
          - "1.17.13"
          - "1.18.10"
          - "1.19.13"
          - "1.20.11"
          - "1.21.4"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-ver }}
      - name: Go Build
        run: |
          gcc --version
          go version
          go build -v .
      - name: Go Test
        if: ${{ matrix.vm-os != 'windows-2022' }}
        run: |
          go test -cover -covermode=atomic -v -count 1 ./...
